### ISSUE TITLE
getaddrinfo enotfound error

### ISSUE THREAD

**Issue by MaksiSoufiane** [mallocator/Elasticsearch-Exporter#118]
# node exporter.js -a 94.23.26.116 -sa user:pass -si myindex -st type1 -t file -tf filename
Elasticsearch Exporter - Version 1.4.0
getaddrinfo ENOTFOUND
getaddrinfo ENOTFOUND
getaddrinfo ENOTFOUND
getaddrinfo ENOTFOUND
Number of calls:        0
Fetched Entries:        0 documents
Processed Entries:      0 documents
Source DB Size:         0 documents

Im using Shield

**Comment by mallocator** [comment]
That looks like the network connection could not be opened. Check whether the IP address is correct and that the proper ports are open.

**Comment by MaksiSoufiane** [comment]
$ curl -u user:pass -XGET 'http://94.23.26.116:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "testcluster",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 5,
  "active_shards" : 10,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}

**Comment by mallocator** [comment]
Well I don't know how else to help with this limited information. ENOTFOUND means that node couldn't connect to a server. That might be network related or rights related or something else completely.

Maybe try the ip address with an http:// prefix? Although I expect that that would not change much.

**Comment by mallocator** [comment]
No further information for this issue. I'm assuming this resolved.
