### ISSUE TITLE
Doesn't work with AWS ES service

### ISSUE THREAD

**Issue by taschmidt** [mallocator/Elasticsearch-Exporter#123]
With AWS's managed ES service (my target server), they don't allow the **/_cluster/state** operation so it errors out [here](https://github.com/mallocator/Elasticsearch-Exporter/blob/master/drivers/elasticsearch.driver.js#L213).  Is that totally necessary?

**Comment by mallocator** [comment]
Is it absolutely necessary? No.

It is necessary for alias support in the current implementation. 

TODO: Investigate AWS compatible alias support call.

**Comment by taschmidt** [comment]
Great, thanks!
