### ISSUE TITLE
ES 5.x support?

### ISSUE THREAD

**Issue by FrodeRennemo** [mallocator/Elasticsearch-Exporter#125]
Hi,

Does this module support elasticsearch version 5.0? I installed via npm, tried to copy all indices between two machines, but it says "The source driver has not reported any documents that can be exported. Not exporting". 

I cloned the project in order to try the same in the v2.0.0 branch, but when I try to install npm packages  npm says "Unsupported platform for elasticsearch-exporter@2.0.0". Im on Windows 10.

Any ideas?

**Comment by mallocator** [comment]
Unfortunately no to both 5.0 and Windows. I have not updated to work with the latest version yet, and I've never tried to run this tool on MS software.

You can probably still force an installation if you change the package.json and remove the os restriction here: https://github.com/mallocator/Elasticsearch-Exporter/blob/master/package.json#L11

It'll probably still not work, but you can give it a shot.

**Comment by adam-ludgate** [comment]
Subscribing to this thread if ES5 support happens to appear in the near future, love this tool

**Comment by mallocator** [comment]
5.x support has been added via the elasticsearch-client driver. You can give it a whirl and check if that works for you.
