### ISSUE TITLE
Export of a big dataset fails for me

### ISSUE THREAD

**Issue by cyrillk** [mallocator/Elasticsearch-Exporter#126]
Hi,

The export fails for me when I try to export a big dataset to a file. Smaller datasets are fine.

```
eexport -a xxx -p 9200 -b file -g xxx -z 100 -T true --overwrite true

Elasticsearch Exporter - Version 1.4.0
Reading source statistics from ElasticSearch
Reading mapping from ElasticSearch
Storing all mapping in meta file xxx.meta
Mapping is now ready. Starting with 0 queued hits.
Reading mapping from ElasticSearch
Storing all mapping in meta file xxx.meta
Mapping is now ready. Starting with 0 queued hits.

<--- Last few GCs --->

[96520:0x103000000]   140695 ms: Mark-sweep 761.2 (809.6) -> 761.2 (810.6) MB, 1996.7 / 0.0 ms  allocation failure GC in old space requested
[96520:0x103000000]   142678 ms: Mark-sweep 761.2 (810.6) -> 761.2 (779.6) MB, 1982.7 / 0.0 ms  last resort gc
[96520:0x103000000]   144503 ms: Mark-sweep 761.2 (779.6) -> 761.2 (779.6) MB, 1824.7 / 0.0 ms  last resort gc


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x227f02c0d39 <JS Object>
    1: fromString(aka fromString) [buffer.js:207] [pc=0x19f52f50710e](this=0x227f0204311 <undefined>,string=0x1423b058fe31 <Very long string[213991219]>,encoding=0x227f02ca069 <String[4]: utf8>)
    2: from [buffer.js:104] [pc=0x19f52f508610](this=0x232f4a4a1671 <JS Function Buffer (SharedFunctionInfo 0x227f02e44a1)>,value=0x1423b058fe31 <Very long string[213991219]>,encodingOrOffset=0x227f02ca0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [/usr/local/bin/node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/usr/local/bin/node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/usr/local/bin/node]
10: node::Buffer::CreateFromString(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
12: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
13: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x19f52d5063a7
```

Thank you.

Kind regards,
Kirill

**Comment by cyrillk** [comment]
I've tried to run export with `--max-old-space-size=600` and `--max-old-space-size=6000` but result is the same.

**Comment by mallocator** [comment]
If you run the node script directly with --max-old-space-size you should also try to add --expose-gc as a flag, as the exporter should try to stay below 90% memory usage if it can access it's own memory usage.

If that doesn't work there's a few things you can try:

1. Set the memory limit lower (--memory.limit or -ml), the default is 0.9 which is 90% usage. Maybe you fetch a lot at once and get over the 10% buffer.
2. Move the import operation to the target database instance. If you're running the script between two instances then network can have a big impact on which database is faster. Running the script on the target database instance means you skip the network wait time.
3. Beef up your target cluster. There's a reason the cluster is slow at accepting documents. The script only starts to fill up memory if it has to queue documents.
4. Play with the step size (--run.step or -rs). A smaller step size might help with huge documents and not overallocating into the gc. 
5. Segment your import. Assuming you're using the elasticsearch driver, you can segment your import and run it at smaller chunks. You can use a custom query to select which documents are exported (--source.query or -sq). This way you can import documents in segments based on timestamps or names - whatever works best with your data.

Finally check out the [performance tuning ](https://github.com/mallocator/Elasticsearch-Exporter#improving-performance) section for some more tips that might help you.

While I hope that helps, don't forget that version 2.0 is still in beta. If all else fails you can always try the previous version (which has almost all of the current features).

**Comment by cyrillk** [comment]
Thank you. Probably, as you suggested, some records very too big. I've changed `-z` parameter to a lower value and it's fine now.
