### ISSUE TITLE
Unable to use Exporter 

### ISSUE THREAD

**Issue by parag90-zz** [mallocator/Elasticsearch-Exporter#130]
Elasticsearch Exporter - Version 2.0.1
Tried to load driver [elasticsearch] that doesnt exist!
Exit code 11: driver doesn't exist

I got this message while running exporter

**Comment by paulobezerr** [comment]
Could you give us the used command?

**Comment by senthilmca90** [comment]
Hi, I used this command, `node exporter.js -a http://localhost:9200 -b http://139.162.246.121:9200/`. I got error.
 
Elasticsearch Exporter - Version 2.0.1
Tried to load driver [elasticsearch] that doesnt exist!
Exit code 11: driver doesn't exist

**Comment by paulobezerr** [comment]
I'm sorry to ask this, but did you do ``npm install``?

**Comment by senthilmca90** [comment]
Yes, I have done `npm install`

**Comment by paulobezerr** [comment]
I cannot reproduce. Sorry :(

**Comment by bfarayev** [comment]
I also tried to reproduce this issue. Without `npm install` I could get the same error as @parag90 but simply doing `npm install` solved the issue

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
