### ISSUE TITLE
Caught exception in Main process: TypeError: Cannot read property 'indices' of undefined

### ISSUE THREAD

**Issue by beeramvishnu** [mallocator/Elasticsearch-Exporter#131]
Here is the command and error
node exporter.js --sourceUseSSL true --sourceAuth admin:ZOO --targetAuth admin:JP0k6 --sourceHost essourceclusterdns --targetUseSSL true --targetHost estargetclusterdns -i .sec-data-9 -j .sec-data-9 -T true -U true -V true -p 443 -q 443

TypeError: Cannot read property 'indices' of undefined
    at IncomingMessage.<anonymous> (/home/xxxx/opt/elasticsearch-exporter/node_modules/elasticsearch-exporter/drivers/es.js:215:44)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
