### ISSUE TITLE
source.size parameter may not be working as expected

### ISSUE THREAD

**Issue by bfarayev** [mallocator/Elasticsearch-Exporter#133]
I've tried to run with `--source.size` equals to 0, 100, 10,000 but each time it was fetching only 500 entries from source.

I'm only using -sh, -si, -th and -tj flags.

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
