### ISSUE TITLE
The source driver has not reported any documents that can be exported. Not exporting.

### ISSUE THREAD

**Issue by gruaig** [mallocator/Elasticsearch-Exporter#134]
Hey wonder can you help me
node exporter.js  -s elasticsearch -a 10.10.209.50 -i elastalert_status -t file -tf filename
Elasticsearch Exporter - Version 1.4.0
The source driver has not reported any documents that can be exported. Not exporting.
Number of calls:	0
Fetched Entries:	0 documents
Processed Entries:	0 documents
Source DB Size:		0 documents

**Comment by lhzw** [comment]
Me too, version 1.4.0.

```
node ~/node_modules/elasticsearch-exporter/exporter.js -a ipa -b ipb
Elasticsearch Exporter - Version 1.4.0
Reading source statistics from ElasticSearch
The source driver has not reported any documents that can be exported. Not exporting.
Number of calls:        0
Fetched Entries:        0 documents
Processed Entries:      0 documents
Source DB Size:         0 documents
```

**Comment by 401825317** [comment]
ME too.

**Comment by 401825317** [comment]
![image](https://user-images.githubusercontent.com/19526136/49209122-960ffc80-f3f4-11e8-901b-f6dcd4a22efe.png)

**Comment by LuckyNemo** [comment]
No one answer it?

**Comment by si24803** [comment]
Hello all.

I also had this problem. Maybe it was an update on ElasticSearch that broke this but I'm using 6.3/6.5 and the problem seems to be a missing header on requests made to the nodes.
I added line 43 to the request.js source file and it seems to fix this issue.
`reqOpts.headers['Content-Type'] = "application/json";`

**Comment by songkaiha** [comment]
Me too,

**Comment by dtorthestudent** [comment]
Me too...

**Comment by liuhll** [comment]
Me too...

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
