### ISSUE TITLE
ES -> ES  not working, always show no documents

### ISSUE THREAD

**Issue by puppywang** [mallocator/Elasticsearch-Exporter#135]
Elasticsearch Exporter - Version 2.0.1
Mapping on target database is now ready
Starting data export
Processed Entries:	0 documents
Source DB Size:		0 documents
No documents have been found in the source database!

statistics.hits is used in exporter.js, but I can't find any where to assign hits value from ES.

```
node exporter.js -sh 192.168.1.10 -si images -th 127.0.0.1
```

**Comment by cujovaisov** [comment]
Same here, also getting `No documents have been found in the source database`

**Comment by gmesika** [comment]
here also... 3 years after
dosent seems that someone is maintaining

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
