### ISSUE TITLE
The driver reported an error: Not enough information has been given to be able to perform an export.

### ISSUE THREAD

**Issue by Future-3** [mallocator/Elasticsearch-Exporter#136]
Elasticsearch Exporter - Version 2.0.1
The driver reported an error: Not enough information has been given to be able to perform an export. Please review the OPTIONS and examples again.
Exit code 4: driver is passing on an error
Processed Entries:      0 documents
Source DB Size:         0 documents
No documents have been found in the source database!

**Comment by Future-3** [comment]
node exporter.js -a 10.251.16.111 -b 10.249.151.62

**Comment by sudheerchamarthi** [comment]
`node exporter.js -a x.x.x.x -i the_hive_2 -b y.y.y.y -i the_hive_3
Elasticsearch Exporter - Version 2.0.1
The driver reported an error: Not enough information has been given to be able to perform an export. Please review the OPTIONS and examples again.
Exit code 4: driver is passing on an error
Processed Entries:	0 documents
Source DB Size:		0 documents
No documents have been found in the source database!`

Getting the same error

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
