### ISSUE TITLE
Failure during Import of Data - Unexpected Token u

### ISSUE THREAD

**Issue by Chadwiki** [mallocator/Elasticsearch-Exporter#67]
I am receiving an error during import of data:
Running the current version of Exporter against ES 1.3.2

![image](https://cloud.githubusercontent.com/assets/6718884/4000966/1a7bca9a-295f-11e4-84f5-eb350978fb03.png)

ES Log:
![image](https://cloud.githubusercontent.com/assets/6718884/4001089/445ac43c-2960-11e4-9e59-6c43327dfc88.png)

**Comment by josegonzalez** [comment]
Oooh I'm definitely seeing this in latest stable - `cat es.data | grep undefined`. The bug I just reported stops me from testing exports using master, but I'd be happy to do so once that is squared away :)

**Comment by mallocator** [comment]
With latest stable you mean 1.4? Development on that has stopped and I'm focussing all of my (unfortunately very sparse) attention to getting 2.0 to stable. On the 1.x branch I'm not surprised that you see this as this was never fixed there.

**Comment by josegonzalez** [comment]
FWIW, you can do the following:

```
sed -i.bak '/^undefined$/d' index.data
```

And that will both cleanup your index data and make a backup of the original data :)
