### ISSUE TITLE
Caught Exception in main process: Type Error: Cannot read property 'settings' of undefined

### ISSUE THREAD

**Issue by BlackRabbitt** [mallocator/Elasticsearch-Exporter#79]
The error log says:
###### 

Elasticsearch Exporter - Version 1.4.0
Reading source statistics from ElasticSearch
Reading mapping from ElasticSearch
Caught exception in Main process: TypeError: Cannot read property 'settings' of undefined
TypeError: Cannot read property 'settings' of undefined
    at IncomingMessage.<anonymous> (/Elasticsearch-Exporter-master/drivers/es.js:338:59)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
Number of calls:    1
Fetched Entries:    0 documents
Processed Entries:  0 documents
Source DB Size:     1049958 documents
###### 

Is this error occured because of Source DB Size. Is the size too large? 

Thank you.

**Comment by thm1118** [comment]
i had same exception .
eexport -a localhost -i heluo-weinxin-zhengwu -b 192.168.10.71 ,index name is  lowercase.

**Comment by mallocator** [comment]
Does your ES cluster accept the setting if you set it manually? Are there any more details in the ElasticSearch log?

**Comment by thm1118** [comment]
i try again, it work now .:)

**Comment by mallocator** [comment]
Without any changes? That's weird.

**Comment by josegonzalez** [comment]
I can replicate this by using an alias for the `sourceIndex`. When switching to the actual index name, all works fine.

**Comment by mallocator** [comment]
Good to know, thanks @josegonzalez 
I'll be sure to consider that with the 2.0 implementation.

**Comment by josegonzalez** [comment]
Yeah, my current hack to is to find the index being aliased - fun with bash! - and then retrieve that one.

**Comment by mallocator** [comment]
Yes, a little late, but I've moved on to other projects. Unfortunately, I can't point you to any other repo that forked and continued the work here, so you'll have to look for another solution, although I believe AI will soon make all of these little tools obsolete. 

Most functionality was broken when ES moved to v6, and I don't even know what version we're on today, so it's no surprise it's broken. If there's huge demand I may come back to this as I was working on a more generic implementation with drivers for different DBs, a web GUI, and other little improvements. For now, consider this project abandoned 😢. One person can only do so much.
