### ISSUE TITLE
Mappings not updated on target correctly

### ISSUE THREAD

**Issue by mpcarl-ibm** [mallocator/Elasticsearch-Exporter#81]
I am trying to copy an index from 1 cluster to another cluster.  Using the options file, I get the following output.

[mpcarl] (master) $: node exporter.js -o meetings.json
Elasticsearch Exporter - Version 1.4.0
Reading source statistics from ElasticSearch
Reading mapping from ElasticSearch
Reading mapping from ElasticSearch
Creating index mapping in target ElasticSearch instance
Creating index mapping in target ElasticSearch instance
Mapping is now ready. Starting with 0 queued hits.
Mapping is now ready. Starting with 0 queued hits.
Host target_host:9200 responded to PUT request on endpoint /meetings with an error:
 {"error":"IndexAlreadyExistsException[[meetings] already exists]","status":400}
Processed 200 of 3611 entries (6%) .....

When I look at the mappings at the end of the job, they don't match the source mappings.  Everything looks to be just defaults.

mappings: {
Meetings: {
properties: {
created_by: {
type: string
}
date_entered: {
type: string
}

versus the source

created_by: {
type: "string",
index: "not_analyzed",
omit_norms: true,
index_options: "docs"
},
date_end: {
type: "date",
format: "dateOptionalTime"
},
date_entered: {
type: "date",
format: "yyyy-MM-dd HH:mm:ss"
},

I also don't understand why it is trying to update the target twice, but maybe that's a different issue.

Elastic version "0.90.7" on both servers.

**Comment by mallocator** [comment]
With the rewrite this should no longer apply.
