### ISSUE TITLE
TypeError: Cannot read property 'num_docs' of undefined

### ISSUE THREAD

**Issue by fosberyi** [mallocator/Elasticsearch-Exporter#82]
Hi Ravi,

I'm getting this error when I try to run the following command:

node exporter.js -a localhost -p 9200 -b 10.128.99.35 -p 9200

I can make curls to both nodes no problem. The error I get is:

Caught exception in Main process: TypeError: Cannot read property 'num_docs' of undefined
TypeError: Cannot read property 'num_docs' of undefined
    at IncomingMessage.<anonymous> (/root/node_modules/elasticsearch-exporter/drivers/es.js:243:58)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
Number of calls:	0
Fetched Entries:	0 documents
Processed Entries:	0 documents
Source DB Size:	0 documents

localhost: v 1.0.1
10.128.99.35: v 0.90.7

Apologies if there's something I'm missing. Thanks!

**Comment by mallocator** [comment]
Closing this since the code base has changed so much it's not really related to 1.x versions anymore.
