### ISSUE TITLE
the mapping error is back with version 1.4.2 

### ISSUE THREAD

**Issue by nidgupta** [mallocator/Elasticsearch-Exporter#90]
host responded to PUT request on endpoint /{index}/_mapping/type/ with an error: 
 {"error":"MapperParsingException[Root type mapping not empty after parsing! Remaining fields:

**Comment by mallocator** [comment]
Thanks for the feedback, I'm currently doing a rewrite to v2.0. With that I hope I'll be able to fix any mapping issues.

**Comment by nidgupta** [comment]
any expected date for the next version?

**Comment by mallocator** [comment]
Nothing set in stone. The base code is done. What's missing now is proper test coverage and getting out all the kinks and bugs. It also depends on whether I will release the MySQL driver (and maybe others) along with the initial release or delay that for a later version. I'd say a few more weeks are necessary, depending on how demanding my other projects (like my job) are.

You can take a look at what's there already by switching to the v2.0.0 branch, but don't expect it to run well (or at all) right now.

**Comment by lighta** [comment]
same error here sad =(
Host localhost:9200 responded to PUT request on endpoint /events/_mapping/event/ with an error:
 {"error":"MapperParsingException[Root type mapping not empty after parsing! Remaining fields:   [events : {mappings={event={properties={@timestamp={type=date, format=dateOptionalTime}, De                                              vice_HashedID={type=string}, IMEI={type=string}, MEID={type=string}, computer={type=string}, configuration={type=string}, details={type=string}, eventGUID={type=string}, eventname={type=st                                              ring}, installGUID={type=string}, ip={type=string}, manufacturer={type=string}, modelName={type=string}, operator={type=string}, platform={type=string}, processId={type=long}, serviceResul                                              t={type=string}, shift={type=string}}}}}]]","status":400}

It's just a matter to not retry to create the mapping if we already have 1 stored.

**Comment by mallocator** [comment]
Thanks for the feedback and sorry to see you sad :'(

Work on 2.0 is still ongoing (but unfortunately very slowly). The new version should take care of this problem.

**Comment by lighta** [comment]
Just try v2, well I can't say now it's the export which is buggy, I'll create a report for you.

**Comment by mallocator** [comment]
Haven't seen this pop up so far in v2, closing for now.
