### ISSUE TITLE
When exporting to a file, not all records are written

### ISSUE THREAD

**Issue by alcanzar** [mallocator/Elasticsearch-Exporter#96]
I believe the last batch of records fetched is not always saved to the file.  For example:

    $ eexport -z 4000  -a es-dev -i titan_opi.2013-12 -d false -g titan_opi.2013-12.export
    Elasticsearch Exporter - Version 1.4.0
    Reading source statistics from ElasticSearch 
    Reading mapping from ElasticSearch
    Storing index mapping in meta file titan_opi.2013-12.export.meta
    Mapping is now ready. Starting with 0 queued hits.
    Reading mapping from ElasticSearch
    Storing index mapping in meta file titan_opi.2013-12.export.meta
    Number of calls:	2
    Fetched Entries:	3080 documents
    Processed Entries:	3080 documents
    Source DB Size:		3080 documents
    Peak Memory Used:	44476912 bytes (63%)
    Total Memory:		74978304 bytes
    $ wc -l *.data
           0 titan_opi.2013-12.export.data

Sometimes it gets all the records

    $ eexport -z 1000 -a es-dev -i titan_opi.2013-12 -d false -g titan_opi.2013-12.export
    Elasticsearch Exporter - Version 1.4.0
    Reading source statistics from ElasticSearch
    Reading mapping from ElasticSearch
    Storing index mapping in meta file titan_opi.2013-12.export.meta
    Mapping is now ready. Starting with 0 queued hits.
    Reading mapping from ElasticSearch
    Storing index mapping in meta file titan_opi.2013-12.export.meta
    Mapping is now ready. Starting with 0 queued hits.
    Number of calls:	2
    Fetched Entries:	3080 documents
    Processed Entries:	3080 documents
    Source DB Size:		3080 documents
    Peak Memory Used:	44660320 bytes (62%)
    Total Memory:		74978304 bytes
    [workmac:~/projects/InContactAPI]$ wc -l *.data
        6160 titan_opi.2013-12.export.data

And sometimes it doesn't:

    $ eexport -z 240 -a es-dev -i titan_opi.2013-12 -d false -g titan_opi.2013-12.export
    Elasticsearch Exporter - Version 1.4.0
    Reading source statistics from ElasticSearch
    Reading mapping from ElasticSearch
    Storing index mapping in meta file titan_opi.2013-12.export.meta
    Mapping is now ready. Starting with 0 queued hits.
    Processed 1200 of 3080 entries (39%)
    Reading mapping from ElasticSearch
    Storing index mapping in meta file titan_opi.2013-12.export.meta
    Mapping is now ready. Starting with 0 queued hits.
    Processed 2400 of 3080 entries (78%)
    Number of calls:	4
    Fetched Entries:	3080 documents
    Processed Entries:	3080 documents
    Source DB Size:		3080 documents
    Peak Memory Used:	39894344 bytes (58%)
    Total Memory:		71423232 bytes
    $ wc -l *.data
        3760 titan_opi.2013-12.export.data

**Comment by alcanzar** [comment]
FYI -- it looks like the 2nd "Storing index mapping in meta file" ends up truncating the file.  So it's data from the beginning of the file that is missing.

**Comment by alcanzar** [comment]
This patch "fixes" it for me, but I'm not a node.js expert

    --- /usr/local/lib/node_modules/elasticsearch-exporter/drivers/file.js	2015-05-13 10:49:11.000000000 -0500
    +++ drivers/file.js	2015-05-13 10:51:18.000000000 -0500
    @@ -3,7 +3,6 @@
     var through = require('through');
     var zlib = require('zlib');
     var path = require('path');
    -var metaStored = false;
     
     /**
      * Resets all stored states of this driver and allows to start over from the beginning without restarting.
    @@ -14,7 +13,6 @@
         exports.buffer = '';
         exports.items = [];
         exports.fileReader = null;
    -    exports.metaStored = false;
     };
     
     /**
    @@ -78,12 +76,6 @@
     }
     
     function createMetaFile(opts, data, callback) {
    -    if (metaStored) {
    -	console.log("Meta data already stored.");
    -      callback();
    -      return;
    -    }
    -    metaStored = true;
         createParentDir(opts);
         fs.writeFile(opts.targetFile + '.meta', JSON.stringify(data, null, 2), { encoding:'utf8' }, function (err) {
             if (err) throw err;
    @@ -219,9 +211,10 @@
             exports.targetStream.queue(data).resume();
             callback();
         } else {
    -	console.log("writing "+data.length);
    -        fs.appendFileSync(opts.targetFile + '.data', data, { encoding: 'utf8' });
    -	callback();
    +        fs.appendFile(opts.targetFile + '.data', data, { encoding: 'utf8' }, function (err) {
    +            if (err) throw err;
    +            callback();
    +        });
         }
     };

**Comment by mallocator** [comment]
Thanks for the patch. 
I'll take a look at the 2.0 branch to see if this applies.

**Comment by mallocator** [comment]
The file driver is completely different in v2 where we actually have individual files for each type and index, so I don't think this applies anymore.
